## 11. Views and Subqueries: CREATE VIEW, DROP VIEW

In this notebook creating views and subqueries and their uses will be covered.

###### Keywords Covered - CREATE VIEW, DROP VIEW

In [1]:
import sqlite3
import pandas as pd

# Connect to database
data_conn = sqlite3.connect("pokemon.db")

### CREATE VIEW

Use: Creating an object out of a query to make it reuseable. This ensures consistency when doing the same query multiple times. It also enhances security by restriciting access to specific data in the table/tables.

*Syntax: CREATE VIEW view_name AS*

In [2]:
# Create a view which selects just the fire Pokemon.
data_conn.execute(""" CREATE VIEW fire_pokemon AS
                      SELECT * 
                      FROM pokemon
                      WHERE type1 = 'fire'""")

In [3]:
# Display the data in the view.
pd.read_sql("""SELECT * 
               FROM fire_pokemon
               LIMIT 12""", con=data_conn)

,id,name,type1,type2,height,weight,dex_entry,image_url,elo,wins,losses
0,4,Charmander,fire,NaN,0.6,8.5,"From the time it is born, a flame burns at the...",https://raw.githubusercontent.com/PokeAPI/spri...,1500.0,0,0
1,5,Charmeleon,fire,NaN,1.1,19.0,"If it becomes agitated during battle, it spout...",https://raw.githubusercontent.com/PokeAPI/spri...,1500.0,0,0
2,6,Charizard,fire,flying,1.7,90.5,Its wings can carry this Pokémon close to an a...,https://raw.githubusercontent.com/PokeAPI/spri...,1500.0,0,0
3,37,Vulpix,fire,NaN,0.6,9.9,"In its belly burns a fire, which Vulpix spits ...",https://raw.githubusercontent.com/PokeAPI/spri...,1500.0,0,0
4,38,Ninetales,fire,NaN,1.1,19.9,The coat of gleaming golden fur is quite magni...,https://raw.githubusercontent.com/PokeAPI/spri...,1500.0,0,0
5,58,Growlithe,fire,NaN,0.7,19.0,They patrol their territory in pairs. I believ...,https://raw.githubusercontent.com/PokeAPI/spri...,1500.0,0,0
6,59,Arcanine,fire,NaN,1.9,155.0,Snaps at its foes with fangs cloaked in blazin...,https://raw.githubusercontent.com/PokeAPI/spri...,1500.0,0,0
7,77,Ponyta,fire,NaN,1.0,30.0,These Pokémon live in herds out in the grassla...,https://raw.githubusercontent.com/PokeAPI/spri...,1500.0,0,0
8,78,Rapidash,fire,NaN,1.7,95.0,"Fiery mane aglow, Rapidash darts like an arrow...",https://raw.githubusercontent.com/PokeAPI/spri...,1500.0,0,0
9,126,Magmar,fire,NaN,1.3,44.5,Legend has it that this Pokémon was born from ...,https://raw.githubusercontent.com/PokeAPI/spri...,1500.0,0,0
10,136,Flareon,fire,NaN,0.9,25.0,Flames burn within a saclike organ inside this...,https://raw.githubusercontent.com/PokeAPI/spri...,1500.0,0,0
11,146,Moltres,fire,flying,2.0,60.0,There are stories of this Pokémon using its ra...,https://raw.githubusercontent.com/PokeAPI/spri...,1500.0,0,0

### DROP VIEW

Use: Deletes the view.

In [4]:
# Delete the fire_pokemon view.
data_conn.execute("""DROP VIEW fire_pokemon""")

In [5]:
# Try to display the data in the view.
pd.read_sql("""SELECT * 
               FROM fire_pokemon
               LIMIT 12""", con=data_conn)

DatabaseError: Execution failed on sql 'SELECT *
               FROM fire_pokemon
               LIMIT 12': no such table: fire_pokemon

This now raises an error as the view has been dropped.

### Subqueries

Use: A subquery is a query nested within another query. These can have uses like:

*    Applying aggregate functions (e.g AVG, SUM) dynamically.
*    Selecting rows based on the requirements returned by the subquery.

### Single row Subqueries

These are subqueries which return one result.

Below we will get the largest height value, and then use that to return the data on the pokemon with that height.

In [6]:
# View the data on the tallest Pokemon.
pd.read_sql("""SELECT id, name,	type1, type2, height, weight, dex_entry
               FROM pokemon
               WHERE height = (SELECT MAX(height) from pokemon)""", con=data_conn)

,id,name,type1,type2,height,weight,dex_entry
0,890,Eternatus,poison,dragon,20.0,950.0,"It was inside a meteorite that fell 20,000 yea..."

### Multi Row Subqueries

Use: A subquery that returns many rows based on the double query.

Below we will return all fire Pokemon in the first 250 Pokemon (main query) that are above average weight (subquery).

In [7]:
pd.read_sql("""SELECT id, name,	type1, height, weight
               FROM pokemon
               WHERE weight > (SELECT AVG(weight) from pokemon)
               AND id <= 250
               AND type1 = 'fire'""", con=data_conn)

    id        name type1  height  weight
0    6   Charizard  fire     1.7    90.5
1   59    Arcanine  fire     1.9   155.0
2   78    Rapidash  fire     1.7    95.0
3  157  Typhlosion  fire     1.7    79.5
4  244       Entei  fire     2.1   198.0
5  250       Ho Oh  fire     3.8   199.0