## 7. Math Functions: ABS, ROUND, RANDOM, TOTAL, SQRT, SQUARE, CEILING, FLOOR, POWER, EXP, LOG, MOD, COS, SIN, TAN, PI

In this notebook we will cover the most commonly used math functions, as well as many other useful ones.

###### Keywords Covered - ABS, ROUND, RANDOM, TOTAL, SQRT, SQUARE, CEILING, FLOOR, POWER, EXP, LOG, MOD, COS, SIN, TAN, PI

In [1]:
import sqlite3
import pandas as pd

# Connect to database
data_conn = sqlite3.connect("pokemon.db")

data_conn.execute("DROP TABLE pokemon_item_price") # Delete to refresh any prior changes.

# Create the tables for the Pokémon items and their prices.
data_conn.execute("CREATE TABLE pokemon_item_price \
                        (item_id INTEGER PRIMARY KEY AUTOINCREMENT, \
                         name TEXT NOT NULL, \
                         price INTEGER NOT NULL)")

# Insert data into the two tables.
data_conn.execute("INSERT INTO pokemon_item_price (name, price) VALUES \
                ('Rice Ball', 5), ('Candy', 10), ('Poké Ball', 200), ('Great Ball', 600), \
                ('Potion', 300), ('Super Potion', 700), ('Hyper Potion', 1200)")

# Display the dat we will be using for examples.
data = data_conn.execute("SELECT * FROM pokemon_item_price").fetchall()
df = pd.DataFrame(data)
df.columns= ['ID', 'Name', 'Cost',] # Add column names.
df

   ID          Name  Cost
0   1     Rice Ball     5
1   2         Candy    10
2   3     Poké Ball   200
3   4    Great Ball   600
4   5        Potion   300
5   6  Super Potion   700
6   7  Hyper Potion  1200

### ABS

Use: Returns the absolute value of a number.

### ROUND

Use: Rounds a number to an integer or a specified number of decimal places.

*Tip: Choose how many decimal places to round to by using the second parameter, e.g. ROUND(x, 2).*

### RANDOM

Use: Generates a random number.

Below we will show these. You can also use the +, -, / and * symbols to perform arithmetic with a column.

In [2]:
# Showing the ABS, ROUND and RANDOM functions.
func = data_conn.execute("SELECT price, ABS(price), price * 2, price / 7.2, ROUND(price / 7.2, 2), RANDOM() FROM pokemon_item_price").fetchall()
df = pd.DataFrame(func) # Convert list to dataframe.
df.columns= ['Price', 'ABS(Price)', 'price x 2', 'price / 7.2', 'ROUND(price / 7.2)', 'RANDOM'] # Add column names.
df

,Price,ABS(Price),price x 2,price / 7.2,ROUND(price / 7.2),RANDOM
0,5,5,10,0.694444,0.69,-4981427321526556888
1,10,10,20,1.388889,1.39,-966943803826398748
2,200,200,400,27.777778,27.78,-9132558627082690873
3,600,600,1200,83.333333,83.33,-8261774591246751602
4,300,300,600,41.666667,41.67,4644560348745163204
5,700,700,1400,97.222222,97.22,1700088830618023511
6,1200,1200,2400,166.666667,166.67,-4417495036575295761

### TOTAL

Use: Returns the sum of a column. Returns 0 if no non-NULL values.

*Tip: TOTAL always returns a float value, even if it is adding up integer values.*

### SUM

Use: Returns the sum of a column.

*Tip: SUM will return NULL only when there are no non-NULL values to add together.*

### MIN

Use: Finding the smallest number in a column.

### MAX

Use: Finding the largest number in a column

### AVG

Use: Finding the mean average of a column.

### COUNT

Use: Counting the amount of rows in a column.

In [3]:
func = data_conn.execute("SELECT MIN(price), MAX(price), AVG(price), SUM(price), TOTAL(price), COUNT(price) FROM pokemon_item_price").fetchall()
df = pd.DataFrame(func) # Convert list to dataframe.
df.columns= ['MIN(price)', 'MAX(price', 'AVG(price)', 'SUM(price)', 'TOTAL(price)', 'COUNT(price)'] # Add column names.
df

   MIN(price)  MAX(price  AVG(price)  SUM(price)  TOTAL(price)  COUNT(price)
0           5       1200  430.714286        3015        3015.0             7

#### List of other math functions in SQL. Most available though enabling the SQLITE_ENABLE_MATH_FUNCTIONS flag in SQLite.

| Function   | Description                                                                 | Syntax                                            |
|:-----------|:----------------------------------------------------------------------------|:--------------------------------------------------|
| SQRT     | Returns the square root of a numeric value.                                 | SELECT SQRT(value)                                |
| SQUARE   | Returns the square of a numeric value.                                      | SELECT SQUARE(value)                              |
| CEILING  | Returns the smallest integer greater than or equal to a numeric value.      | SELECT CEILING(value)                             |
| FLOOR    | Returns the largest integer less than or equal to a numeric value.          | SELECT FLOOR(value)                               |
| POWER    | Returns the value of a number raised to the power of another number.        | SELECT POWER(base, exponent)                      |
| EXP      | Returns e raised to the power of the specified number.                      | SELECT EXP(value)                                 |
| LOG      | Returns the natural logarithm of a number.                                  | SELECT LOG(value)                                 |
| MOD      | Returns the remainder of a divison. (modulo operation). % can also be used. | SELECT MOD(Dividend [number being divided], divisor)|
| COS      | Returns the cosine of the specified angle (in radians).                     | SELECT COS(angle)                                 |
| SIN      | Returns the sine of the specified angle (in radians).                       | SELECT SIN(angle)                                 |
| TAN      | Returns the tangent of the specified angle (in radians).                    | SELECT TAN(angle)                                 |
| PI       | Returns the value of pi (3.14159265358979).                                 | SELECT PI()                                       |